stages:
  - dockerize

dockerize:
  image: docker:latest
  stage: dockerize
  services:
    - docker:dind
  before_script:
    - export VSN=${CI_COMMIT_REF_NAME}
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${VSN} .
    - docker push ${CI_REGISTRY_IMAGE}:${VSN}
  after_script:
    - docker logout ${CI_REGISTRY}
  only:
  - tags
  - branches
  - push
  - external
  - web
